### ISSUE TITLE
Feature Request: pip-Paket

### ISSUE THREAD

**Issue by dr-br** [thomascamminady/kitcolors#1]
Hallo Thomas,
könntest du aus deinem Paket eventuell ein pip-Paket machen? Das wäre super.
Dann würde ein einfaches

```
pip install https://github.com/thomascamminady/kitcolors.git
```
die KIT-Farben noch einfacher verfügbar machen :)

Grüße
Samuel

**Comment by thomascamminady** [comment]
Gute Idee! Sollte ich am Wochenende zu kommen :)

**Comment by thomascamminady** [comment]
Alles klar, du kannst jetzt einfach
```
pip install kitcolors
```
ausführen. Das Paket lebt in pypi: https://pypi.org/project/kitcolors/

Und dann einfach:
```python

from kitcolors import green, purple10,blue13

```

Danke für den Hinweis!

**Comment by dr-br** [comment]
Das war aber ein frühes Wochenende!
Danke und Grüße ;)

**Comment by thomascamminady** [comment]
Passte dann irgendwie doch :) Ich habe auch das Interface noch ein wenig geändert. Hoffentlich ist dabei nichts kaputt gegangen :)
